In [19]:
import pandas as pd
df=pd.read_csv("dataset.csv")
df

    age   salary  experience
0  25.0  50000.0         2.0
1  30.0      NaN         5.0
2   NaN  60000.0         3.0
3  35.0  80000.0         NaN
4  40.0  90000.0        10.0
5  28.0      NaN         4.0
6   NaN  75000.0         6.0
7  32.0  72000.0         NaN

In [12]:
new_df=df.iloc[:]
new_df["age"]=new_df["age"].fillna(new_df["age"].mean())
new_df["experience"]=new_df["experience"].fillna(new_df["experience"].median())
new_df["salary"]=new_df["salary"].fillna(new_df["salary"].mean())
new_df

         age        salary  experience
0  25.000000  50000.000000         2.0
1  30.000000  71166.666667         5.0
2  31.666667  60000.000000         3.0
3  35.000000  80000.000000         4.5
4  40.000000  90000.000000        10.0
5  28.000000  71166.666667         4.0
6  31.666667  75000.000000         6.0
7  32.000000  72000.000000         4.5

In [14]:
x=new_df[["age","experience"]]
y=new_df["salary"]

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)
model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print("Model trained and Predicted Successfully")

Model trained and Predicted Successfully